# Generated by Django 5.0.4 on 2024-07-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
